# Generated by Django 6.0.6 on 2026-09-20 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax_price',
        ),
    ]
